main:
  MAX_THREADS: 3
  ACTIVE_DISCORD: True
  ACTIVE_SPREADSHEET: True
  ACTIVE_POSTGRESQL: True

discord:
  WEBHOOK_URL: "***"

spreadsheet:
  SHEET_KEY: "***"
  CREDENTIALS_PATH: "***"

postgresql:
  DB_HOST: "***"
  DB_NAME: "***"
  DB_USER: "***"
  DB_PASSWORD: "***"
  DB_PORT: "***"
